---
- hosts: all
  sudo: yes
  vars_files:
    - vars.yml
  vars_prompt:
    - name: "db_pw"
      prompt: "Database password for user {{ gitlabUser }}"
      private: yes
      confirm: yes
  roles:
    - { role: ruby }
    - { role: $databaseType, db_password: $db_pw }
    - { role: gitlab, db_password: $db_pw }
    - { role: nginx }
